apiVersion: v1
kind: Pod
metadata:
  name: my-vault
  labels:
    app.kubernetes.io/name: my-vault
spec:
  containers:
  - name: my-vault
    image: vault
    ports:
    - name: vault-pod-port
      containerPort: 8200
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: my-vault
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: my-vault
  ports:
  - port: 8200
    targetPort: vault-pod-port
