apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-itdt
spec:
  selector:
    matchLabels:
      app: my-itdt
  replicas: 2
  template:
    metadata:
      labels:
        app: my-itdt
    spec:
      containers:
      - name: itdt-container
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
          name: my-itdt-port
        env:
        - name: REACT_APP_USERNAME
          value: hrenaki
        - name: REACT_APP_COMPANY_NAME
          value: itmo
---
apiVersion: v1
kind: Service
metadata:
  name: my-itdt
spec:
  type: NodePort
  selector:
    app: my-itdt
  ports:
  - port: 3000
    targetPort: my-itdt-port